version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ask_slimov
      MYSQL_DATABASE: ask_slimov
      MYSQL_USER: ask_slimov
      MYSQL_PASSWORD: ask_slimov
  web:
    build: .
    depends_on:
      - db
    command: bash -c 'python ask_slimov/manage.py collectstatic --noinput && python ask_slimov/manage.py createcachetable && python ask_slimov/manage.py makemigrations && python ask_slimov/manage.py migrate && /usr/local/bin/gunicorn ask_slimov.wsgi:application -w 4 -b :8000 --chdir /code/ask_slimov'
    volumes:
      - .:/code
    ports:
      - 8000:8000
    expose:
      - 8000
    restart: always
    links:
      - db
  nginx:
    image: "stevecrozz/nginx-push-stream:master"
    volumes:
      - ./docker/nginx:/etc/nginx
      - ./ask_slimov:/code
      - ./static:/static
    command: "/usr/local/nginx/sbin/nginx -c /etc/nginx/nginx.conf"
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: always
    links:
      - web
