# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ask_slimov', '0003_auto_20151115_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-correct', '-date', '-likes']},
        ),
    ]
