# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_slimov', '0004_auto_20161105_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u0422\u0435\u0433', 'verbose_name_plural': '\u0422\u0435\u0433\u0438'},
        ),
    ]
