# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_slimov', '0005_auto_20170107_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[(b'GR', b'success'), (b'DB', b'primary'), (b'B', b'default'), (b'RE', b'danger'), (b'BL', b'info')], default=b'default', max_length=2, verbose_name=b'\xd0\xa6\xd0\xb2\xd0\xb5\xd1\x82'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=30, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
    ]
