# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_slimov', '0008_auto_20170107_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlike',
            options={'verbose_name': '\u041b\u0430\u0439\u043a \u043e\u0442\u0432\u0435\u0442\u0430', 'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438 \u043e\u0442\u0432\u0435\u0442\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': '\u041b\u0430\u0439\u043a \u0432\u043e\u043f\u0440\u043e\u0441\u0430', 'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432'},
        ),
    ]
